- src/stateDirectives.js
Fix the tagName comparism to make ui-sref also work inside an SVG.
> fix($StateRefDirective): resolve support for svg anchor elements #1667

- LICENSE
Copyright notices must reflect the current year. This commit updates the listed year to 2015 with a starting year of 2013.
https://github.com/angular-ui/ui-router/commit/2309474d479d2e27e0700db972a10862f4792a3f
> style(License): update copyright year to range

- src/state.js
- test/stateSpec.js
Previously, it was not possible to match all descendant states without
matching the parent state.
e.g. `about.*.**` would not match state `about.person.item`
I want to be able to match all of the `about` child states, but not the `about` state.
> fix($state): allow about.*.** glob patterns

- src/urlMatcherFactory.js
- test/urlMatcherFactorySpec.js
I noticed when using an array of uuids in a URL that the URL Matcher would only unquote the first dash it found. The fix was pretty straight forward and I have added tests.
> fix($urlMatcherFactory): unquote all dashes from array params

- config/jsdoc.js
- package.json
Remove the jsdoc dependency since ng-doc is now being used
closes #1729
> chore: remove jsdoc

- src/state.js
- test/stateSpec.js
After preventDefault is fired in stateChangeStart, a stageChangeCancel event will be launched.
Rebased and squashed version of #1090 as requested (original PR wasn't mine).
> feat($state): broadcast $stateChangeCancel event when event.preventDefau

- src/urlMatcherFactory.js
- test/urlMatcherFactorySpec.js
> fix($urlMatcherFactory): regex params should respect case-sensitivity

- src/state.js
- test/stateSpec.js
- modiefied options.reload parameter in transitionTo method to accept the
following:
{reload : true} will reload all states
{reload : 'foo.bar'} will reload foo.bar, and any children
{reload : stateObj} will reload state found in stateObj, and any
children.
- added 'state' parameter(string|object) to $state.reload method,
to be passed to $state.transitionTo method as the reload option.
- test the $state.reload with state parameter
> feat($state): added 'state' to state reload method (feat no.1612)

- src/state.js
- test/stateSpec.js
> Allow resolve params to be injected into controllerProvider

- src/state.js
- src/urlRouter.js
- test/stateSpec.js
- test/urlRouterSpec.js
Allow setting the `#` param to update the location fragment; e.g.: `ui-sref="page({name: 'name', '#': 'frag'})"` or `$state.go('page', {name: 'name', '#': 'frag'})`
Improving upon #1855
> feat($state): support URLs with #fragments

- src/stateDirectives.js
Fix 'Invalid Calling Object' error in IE11
> fix(uiSref): use Object's toString instead of Window's toString

- src/stateDirectives.js
- test/stateDirectivesSpec.js
When generating new $state definitions through lazy loaded content, `uiSrefActive` will not reflect class changes on the associated anchor tag as the $state definition was not available in the initial stack. 
---
By pushing a *dummy* state definition to the initial stack of states found on application initialization with the `lazy: true` flag, class reflection onto the view is now working. However, this does not hold true (entirely) when launching your application **on** a lazy loaded state. 
Take the following structure: 
```js
$stateProvider.state('home', { url: '/' });
$stateProvider.state('home.lazy1', { url: '/l1' }); // State definition is added in a module loaded during runtime.
$stateProvider.state('home.lazy2', { url: '/l2' }); // State definition is added in a module loaded …
```
> fix(uiSrefActive): Apply active classes on lazy loaded states

- src/urlMatcherFactory.js
- test/stateSpec.js
Fixes breaking change in 0.2.14 where parameters no longer were allowed to have default values of `0`, `false`, `''`, or `undefined`.
Fixes: #1915
> fix($state) The `is` check on type `any` will always return true.

- src/state.js
- test/stateSpec.js
> feat($state): Inject templateProvider with resolved values

- index.js
- package.json
Added `ui.router` to module exports so that after installing via npm, the package can be required in the angular module dependency list such as:
```angular.module('myApp', [require('angular-ui-router')]);```
This is helpful for Browserify and Webpack.
> refactor(commonjs): Added support for commonjs

- src/stateDirectives.js
- test/stateDirectivesSpec.js
This pull request will allow the usage of both `ui-sref-active` and `ui-sref-active-eq` on the same element. 
One use case includes menus with expanding states where a parent element can be both `active` and `open`, such as in this example:
```html
<ul>
<li ui-sref-active="open" ui-sref-active-eq="active">
<a ui-sref="home"></a>
<ul>
<li ui-sref-active-eq="active">
<a ui-sref="home.view1"></a>
</li>
<li ui-sref-active-eq="active">
<a ui-sref="home.view2"></a>
</li>
</ul>
</li>
<li ui-sref-active="open" ui-sref-active-eq="active">
<a ui-sref="account"></a>
<ul>
<li ui-sref-active-eq="active">
<a ui-sref="account.view1"></a>
</li>
<li ui-sref-active-eq="active">
<a ui-sref="account.view2"></a>
</li>
<li ui-sref-active-eq="active">
<a ui-sref="account.view3"></a>
</li>
</ul>
</li>
</ul>
``` …
> feat(uiSrefActive): allow active & active-eq on same element

- src/view.js
- src/viewDirective.js
The old $viewContentLoaded event wasn't needed for the one internal
client (ui-view) because ui-view always ignores that event and acts on
a $stateChangeSuccess event that follows right behind anyway.
And it wasn't as useful to external clients as it could be because
it wasn't delivered on every view update -- it was delivered only
on state transitions that activate a state defining a view, and
didn't deal with inheritance.
Also, neither $viewContentLoading nor $viewContentLoaded events
contained the name of the view loading or loaded.
This change makes $viewContentLoading and $viewContentLoaded be
emitted always in pairs, before/after updateView does the work of
actually loading the view, and both events include the name of the
view being loaded.
This is a breaking change for users of …
> fix(ui-view): change $viewContentLoading to pair with $viewContentLoaded

- src/stateDirectives.js
- test/stateDirectivesSpec.js
- test/stateSpec.js
- Refactor StateRefDirective for better modularity
- Drop key restrictions on ui-sref-opts
- Improves performance over prior implementation with no extra $eval()’s
Fixes #395, #900, #1932
cc: @kasperlewau @christopherthielen
> feat(uiState): add ui-state directive

- src/urlMatcherFactory.js
- test/urlMatcherFactorySpec.js
Squashed params were ignoring a missing slash before the param so things
like /users123 would match /url/:id
Fixes #2064
> fix(urlMatcherFactory): include the slash in squashed params

- src/state.js
- test/stateSpec.js
Fixes issue with changes to $stateParams leaking from one test case into another. Functionality is otherwise unaffected.
> $stateParams reset between tests

- src/urlMatcherFactory.js
- test/urlMatcherFactorySpec.js
> fix(UrlMatcherFactory): Correct trailing slash of terminal optional parameter

- src/urlRouter.js
- test/urlRouterSpec.js
- Add additional check for situations where `pushState` is not properly supported
> fix(urlRouter): add check using `$sniffer`

- src/params/param.ts
- src/params/type.ts
- src/url/urlMatcher.ts
> feat(urlMatcher): add raw encoding flag to Type

- README.md
Its currently `transitionProvider` in the readme which is not what it is actually :smile:
> Fix incorrect name of transitionsProvider on readme

- src/urlMatcherFactory.js
The doc comment for `UrlMatcher.prototype.validates` was missing the 's' on validates. In other words,
`@name ui.router.util.type:UrlMatcher#validate`
to
`@name ui.router.util.type:UrlMatcher#validates`
https://github.com/angular-ui/ui-router/issues/2203
> Regarding documentation typo #2203

- src/state.js
I spent a while stepping through the code to work out why the extra parameters I was passing to `$state.go()` weren't appearing in `$stateParams`. I've added a sentence to clarify why that is.
> Improved $state.go documentation

- src/urlRouter.js
- test/urlRouterSpec.js
Sometimes url can be matched by several different rules. Now it will be handled by the first rule in order of appearance. So it causes some issues. It would be better to match states from more specified to common.
Angular-route already has same issue https://github.com/angular/angular.js/issues/8266
So, I propose include this fixes here, because is ui-router more powerful and flexible library.
> fix($urlRouter): resolve clashing of routes

- src/state.js
- test/stateSpec.js
Modify state data inheritance to use prototypical inhertiance rather than Angular's extend method to enable more flexibility in handling state data.
I'm currently working on a project that implements Material Design via Angular Material. We've implemented a global [FAB](https://www.google.com/design/spec/components/buttons-floating-action-button.html) by attaching information about what the FAB should do to the state definition. For example:
```javascript
angular.module('MyMaterialDesignProject')
.config(function($stateProvider) {
$stateProvider
.state('foo', {
url: '/foo',
data: {
primaryAction: {
onClick: function($state) {
$state.go('foo.bar');
}
}
}
})
.state('foo.bar', {
url: '/bar'
});
});
```
When we arrive at `foo.bar` we need to be able to tell if `data.primaryAction` is defined …
> feat($state): make state data inheritance prototypical

- src/urlMatcherFactory.js
- test/urlMatcherFactorySpec.js
As per https://github.com/angular-ui/ui-router/issues/983#issuecomment-145288637
> feat(UrlMatcher): Add param only type names

- src/urlMatcherFactory.js
- test/urlMatcherFactorySpec.js
Reverts angular-ui/ui-router#2289
After talking with @christopherthielen, this likely breaks cases that we realized we don't have test coverage for, so that needs to be fixed before this can be addressed. Sorry for the confusion.
> Revert "feat(UrlMatcher): Add param only type names"

- src/viewDirective.js
- test/viewDirectiveSpec.js
> $destroy event is triggered before animation ends

- src/common.js
- src/stateDirectives.js
- test/stateDirectivesSpec.js
This pull request is based on the suggestion by @nateabele on issue #1431. It enables `ui-sref-active` to be passed an expression that should evaluate to an object hash with the `activeClass` and `state` properties. If `state` is provided, `activeClass` is applied to its element if the current active state includes `state`, even if `state` is abstract. It works even if `ui-sref` is found neither on the element nor on any of its children. Furthermore, if `state` is provided, it takes precedence over the state exposed by `ui-sref`. Hope it helps to close #1431 :)
> feat(uiSrefActive): provide a ng-{class,style} like interface

- src/urlMatcherFactory.js
- test/urlMatcherFactorySpec.js
- Adds support for optional spaces in url param typing, i.e. `url:
'foo/{bar: int}'`
> feat(urlMatcher): add support for optional spaces

- src/stateFilters.js
- test/stateFiltersSpec.js
Add parameters to the $IncludedByStateFilter:
- params
- options
This allows to use more parameters on this filter and not only the `fullOrPartialStatename` parameter.
Thanks to this improvement, the following now works (takes in account the id param):
`<div ng-show="'**.foo.**' | includedByState:{id: 'new'}">It works</div>`
Closes #1735
> feat($IncludedByStateFilter): add parameters to $IncludedByStateFilter

- src/common/common.ts
- src/ng1/angular1.ts
- Add `$resolve` service for exposing helper as an injectable
This is a WIP, and is in need of refinement. This also needs tests obviously, and perhaps documentation needs to be restored. Perhaps this also needs to be moved to a separate file.
Thoughts/comments?
> feat(resolve): add $resolve service

- src/state.js
- test/stateSpec.js
Re-added the saved hash before broadcasting $stateChangeStart. This way, libraries using this event to do their magic will have the hash accessible through toParams. (e.g. https://github.com/Narzerus/angular-permission)
Thoughts/comments ?
> fix(transitionTo): re-added the saved hash before broadcasting event

- src/common.js
Fixes #2327, kudos to @pocesar
> fix(common.js): "Cannot read property 'params' of undefined" errors

- src/stateDirectives.js
- test/stateDirectivesSpec.js
This PR makes sure the active classes are applied during the directive compilation phase so that they are available even after `$stateChangeSuccess` has already been fired.
This patch was originally developed for `1.0.0alpha0`, but since the test for it didn't pass on master either, I've backported it.
Plunkr showing the issue: https://plnkr.co/edit/z3kdm41eyuXK052fsflH?p=preview
> fix(uiSrefActive): update the active classes when compiled

- src/urlMatcherFactory.js
The current implementation of the yuicompressor throws an error when minifying the defaultTypes of the urlMatcherFactory because int is an invalid property id.
Changed the property names to string values.
> fix($urlMatcherFactory): Fix to make the YUI Javascript compressor work

- src/resolve.js
Found a spelling mistake -
`caues` → `cause`
> docs(resolve): fix a typo

- src/viewDirective.js
- test/viewDirectiveSpec.js
fix(ui-view) use static renderer when animations are not enabled
closes #2485
> feat(ui-view): Add noanimation attribute to specify static renderer.

- src/viewDirective.js
- test/viewDirectiveSpec.js
> Expose animation promises

- src/ng1/viewDirective.ts
- test/viewDirectiveSpec.js
- Adds two promises `$animEnter`, `$animLeave` to the ui-view's element data object (`element.data('$uiView', viewData)`)
- Reverts `noanimation` workaround code from PR #2497
- Reverts the code that deferred the `scope.destroy()` until the ui-view animated out in PR #2346
> Expose animation promises as element data

- src/transition/transitionService.ts
Hey,
We should use `console.error` here rather than `console.log` to benefit from the browser's error-specific logging features (e.g. stack trace display).
> fix(transition/transitionService): uses console.error to log error in default error handler

- src/resolve/resolvable.ts
- src/resolve/resolveContext.ts
- test/resolveSpec.ts
This PR passes through `$injector.strictDi` to `$injector.annotate` calls. At present, if a resolve function is unannotated and `$injector.strictDi` is `true`, an error is not thrown in contrast to the expected behavior for angular injectables.
> fix(src/resolve): use injector's strictDi value in calls to .annotate

- src/common/common.ts
- src/ng1/services.ts
- src/ng1/viewDirective.ts
- src/state/hooks/resolveHooks.ts
- src/state/interface.ts
- src/state/stateBuilder.ts
- src/view/view.ts
- test/stateSpec.js
- test/viewDirectiveSpec.js
Add a new injectable `$resolve$` for each node.  `$resolve$` contains the resolved data available for injection in that node.
Implement `scope.$resolve` support like ngRoute.  Allows routing to components using a template like 
```
.state('foo', {
template: '<user-component user="$resolve.user"></user-component>',
resolve: { user: UserService => UserService.getUser(); }
});
```
> Implement `resolveAs`

- src/ng1/viewDirective.ts
- test/viewDirectiveSpec.js
After instantiating the controller, will fire its $onInit if defined.
Closes #2559
> feat(uiView): Fire the $onInit hook

- src/common/common.ts
- src/common/trace.ts
- src/ng1.ts
- src/ng1/interface.ts
- src/ng1/services.ts
- src/ng1/stateDirectives.ts
- src/ng1/viewDirective.ts
- src/ng1/viewsBuilder.ts
- src/ng2/interface.ts
- src/ng2/uiView.ts
- src/ng2/viewsBuilder.ts
- src/path/node.ts
- src/path/pathFactory.ts
- src/resolve/resolveContext.ts
- src/router.ts
- src/state/hooks/viewHooks.ts
- src/state/stateBuilder.ts
- src/state/stateObject.ts
- src/state/stateRegistry.ts
- src/transition/transition.ts
- src/transition/transitionService.ts
- src/view/interface.ts
- src/view/templateFactory.ts
- src/view/view.ts
- test/resolveSpec.ts
- test/stateSpec.js
- test/viewSpec.ts
- tsconfig.json
- Each framework (ng1/ng2) to provide a `StateBuilder` `views` decorator that understand different keys/values to meet that framework's needs
- The `views` decorator takes `ViewDeclaration`s (the `views` block on the state declaration), and processes them.  It returns normalized framework specific POJOs (i.e. `Ng1ViewDeclaration`s)
- Before a `Transition` begins, each normalized `ViewDeclaration` being activated is converted into a `ViewConfig` and added to the `Node`'s `views` array
- The `ViewService` is responsible for creating an instance of a `ViewConfig` from the `ViewDeclaration`, based on the type of `ViewDeclaration` (registered using `ViewService.viewConfigFactory`)
- Each ViewConfig is bound to the appropriate Node in the "to path"
- During the transition, the `ViewConfig` is …
> refactor(view): refactor how views are loaded and configured.

- sample/app/app.js
Explicitly show the Api Reference is old, also add link to new Documentation (http://angular-ui.github.io/ui-router/site) directly from the sample site. Let me know if i have to change something
> update link on sample page

- src/stateDirectives.js
Fixed memory leaks beetween states with many ui-sref in their templates
> fix(uiSref, uiState): added click unbind to prevent memory leaks

- src/state.js
- test/stateSpec.js
> fix(state): fail transition on exceptions in transition handler

- src/common/strings.ts
This is my marginal contribution to resolving https://github.com/angular-ui/ui-router/issues/2693
To be honest I don't know the codebase well enough to be of much use but I thought that `strings.ts` seemed generic enough for me to do something.  :tulip:
> Made strings.ts noImplicitAny compliant

- src/ng2/uiView.ts
Newly created components need an initial change detection to be fired manually.
Perhaps this is only a problem when the components are using the OnPush ChangeDetectionStrategy.  Without this fix, components don't load data until some browser event fires - i.e. click, etc.
> ng2 - Enable change detection for route components

- src/ng1/directives/stateDirectives.ts
fixes #2806
https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnbind-is-deprecated
> fix(StateService): remove jQuery deprecated feature

- src/resolve/resolvable.ts
The RXWAIT resolve policy is supposed to wait for the resolved observable to begin emitting values, and then provide the observable.  It accomplishes this by first `cache()`ing the observable and then waiting on the result of `toPromise`. However,  RxJS `toPromise` only resolves the promise when the stream completes, not when the first value is emitted as desired.  Adding `take(1)` before `toPromise` will cause the stream to complete after 1 value is emitted, at what point the original stream can be returned.
Also, the `cache()` without a buffer size will cause all old results to be replayed to new subscribers.  Setting a buffer size of 1 will cause only the most recent emitted value to be replayed.
> fix(Resolve): prevent RXWAIT from waiting for the observable to complete

- src/transition/hookBuilder.ts
- src/transition/hookRegistry.ts
- src/transition/interface.ts
- src/transition/transitionHook.ts
- test/core/hookBuilderSpec.ts
Fix a bug where queued hooks are called even if they are deregistered (#2928)
> fix(transitionHook): Prevent queued hookFn to be called if deregistered

- src/transition/transition.ts
The thrown Error `"Dependency Injection token not found: ${stringify(token)}"` needs back ticks as well as the `stringify` function to be imported. 
Plunkr: http://embed.plnkr.co/1PNtxj674kHsXAxJIiAz/ (open console to see uncaught exception with bug)
> Fixed broken template literal syntax in `getResolveValue`.

- src/ng1/directives/stateDirectives.ts
Since jQuery 3.0, both .bind() and .unbind() have been deprecated.
The suggested replacements are:
jquery.bind() => jquery.on()
jquery.unbind() => jquery.off()
> Replaced deprecated jquery functions

- src/params/paramTypes.ts
- test/ng1/urlMatcherFactorySpec.js
Hello,
I noticed that "~2F" in a param value would be encoded as "~~2F" and then decoded as "~/" ([plunk](http://plnkr.co/edit/Nu2WgFTL36dQnetRByA6?p=preview)). I fixed this so now the encoding/decoding are symmetrical. I think this use case was the reason for encoding "~", and the decoding issue was an oversight.
Note: The problem was in the decode function (valFromString), but I also refactored the encode function (valToString) so that the functions stay easy to read as a pair.
Let me know what you think. If you like it, I also prepared a [branch](https://github.com/angular-ui/ui-router/compare/legacy...cvn:fix-tilde-encoding-legacy) that ports the changes to legacy.
> fix(urlMatcherFactory): fix tilde edge case with "string" encoding

- src/common/coreservices.ts
- `LocationService.url()` has been deprecated in favour of `setUrl()`,
but this interface had not been fully updated.
> fix(common): Remove `url()` from LocationService interface

- CHANGELOG.md
The link to the blog post for 1.0.0-beta.3 was wrong.
> Fix broken link on changelog

- src/stateDirectives.js
> fix(stateDirective): using on to attach an event handler instead of bind

- src/ng1/interface.ts
- test/ng1/stateSpec.js
- test/ng1/viewSpec.ts
Closes #3044. Changes the type of controllerProvider in Ng1ViewDeclaration to IInjectable. Adds 1 test for controller provider in ng1/stateSpec. Updates the controller handling test in ng1/viewSpec to verify that controllerProvider is IInjectable .
> fix(Ng1ViewDeclaration): Make controllerProvider IInjectable

- src/url/urlMatcher.ts
Hello,
I added some documentation about how the tilde encoding interacts with RegExp params. It seemed to only exist in tickets and the code.
My thoughts are that there's no way to fix it so that you wouldn't need to know about the encoding, because there needs to be a way to match both real slashes and encoded slashes.
This makes the RegExp param description quite long, but I couldn't find a better place to put it.
I've also created a [branch](https://github.com/angular-ui/ui-router/compare/legacy...cvn:doc-tilde-encoding-legacy) that ports the change to legacy.
I think this should be enough to close #2540.
> doc(UrlMatcher): RegExp and `string` encoding interaction

- src/ng2/interface.ts
views properties should be of the format `{component: MyComponent}`
I believe this:
```js
views: {
header: HeaderComponent,
body: BodyComponent,
footer: FooterComponent
}
```
should be this:
```js
views: {
header: {component: HeaderComponent},
body: {component: BodyComponent},
footer: {component: FooterComponent}
}
```
> docs(Ng2StateDeclaration): fix views examples

- src/common/coreservices.ts
- src/common/interface.ts
When working with Typescript, you currently need to do something like this to set type correctly:
```typescript
$urlRouterProvider.otherwise(($injector) => {
let myService: MyService = $injector.get('myService');
myService.doSomething();
});
```
With this change, you could instead write the above like this:
```typescript
$urlRouterProvider.otherwise(($injector) => {
$injector
.get<MyService>('myService')
.doSomething();
});
```
> fix($InjectorLike) Optional generic type support

- src/ng1/directives/stateDirectives.ts
This commit fixes the ui-state example in the docs.
> Fix `ui-state` jsdoc syntax typo

- src/ng1/interface.ts
Updated interfaces and documentation to fix #3072
Not sure if documentation looks correct, since I wasn't able to build it correctly.
> docs(Ng1StateHooks): Corrected interface and docs

- src/state.js
- test/stateSpec.js
- test/testUtils.js
This PR supersedes #3029 
Current behaviour:
We are in state A. We start a transition to state B. `$stateChangeStart`
is triggered. Before `$stateChangeSuccess` is triggered for state B, we
start a transition back to state A. No state events are triggered and we
are left hanging without any notification.
Updated behaviour:
When the state change to B is superseded by the state change back to A,
`$stateChangeCancel` is broadcasted on `$rootScope` for the transition from
B -> A. This behaviour makes sure that for every `$stateChangeStart` there
is a corresponding `$stateChange<Success|Error|Cancel>` thus completing the
lifecycle.
Fixes issue #3027
PS: I have modified the existing test suite to assert on new behaviour
> fix($state.transitionTo): trigger $stateChangeCancel appropriately

- src/ng1/directives/viewDirective.ts
- test/viewDirectiveSpec.js
Previously the contents of the initial view were linked and left
undestroyed when the view was replaced with a subview. Because the view
was not destroyed, directives like ngInclude assumed it was safe to
compile and link asynchronous content to it. This would cause a ctreq
error if the asynchronous content required another directive from the
DOM. Now the initial view is either not linked at all or its scope is
properly destroyed.
Closes #1896
> fix(uiView): do not leave initial view scope undestroyed

- src/templateFactory.js
- test/templateFactorySpec.js
This creates a $TemplateFactoryProvider to be able to set a global config option that forces $templateFactory to use $http (which bypasses the security checks, hence the scary name). Added tests and doc for that too. This still defaults to $http on older Angulars as expected.
Fixes the legacy part of #3193. Let me know if there's style issues or missing doc.
> feat($templateFactory): refactor to a Provider to have a $http/$templateRequest switch

- src/directives/stateDirectives.ts
- test/stateDirectivesSpec.js
Using `ui-sref-opts="{ event: ['click', 'dblclick'] }"` we can override the default binding to `ui-sref` directive.
Fixes #3169
> feat(uiSref): Bind ui-sref to DOM events

- release/angular-ui-router.js
- src/urlMatcherFactory.js
- test/urlMatcherFactorySpec.js
fix($state): Negative int parameters in $state allowed
Using a negative parameter in $state.go caused $rootScope:infdig errors; this is now fixed.
Closes #2422
> Negative parameters allowed in $state

- src/directives/stateDirectives.ts
using angular.copy broks states with optional params containing ES6 objects like Map and Set.  The rest of ui-router seems to use extend vs angular.copy, and a deep copy shouldn't be needed here.
this fixes #3189.
> fix(uiSref): replace angular.copy with extend

- CONTRIBUTING.md
The `Purple Labels` section of the CONTRIBUTING.md file isn't rendering properly on Github due to missing images and improperly formatted header. This PR addresses those issues.
> docs(CONTRIBUTING.md): fix missing label images

- src/interface.ts
Found and fixed syntax error in uiCanExit example.
> Added ')' in uiCanExit example

- src/services.ts
In some scenarios, the `$injector` would be asked to annotate without
providing it with the current `strictDi` value, making resolvables not
complain about missing annotations.
This was previously addressed in this PR: https://github.com/angular-ui/ui-router/pull/2602
Yet, it is not working, as can be seen in this plunker, that contains a resolvable without annotations and yet no error is thrown: http://plnkr.co/edit/dd6ptmrUtzPnKLmAJkCY?p=preview
> Fix ngStrictDi support

- src/state.js
- test/stateSpec.js
as long as the last param matches even if the others are different.
Fixes https://github.com/angular-ui/ui-router/issues/3300
@christopherthielen
> fix(state): $state.is will wrongly return true

- src/directives/stateDirectives.ts
This PR attempts to fix a rendering issue with the docs for [`uiSrefActive`](https://ui-router.github.io/ng1/docs/latest/modules/directives.html#uisrefactive). Due to [TypeDoc not automatically escaping HTML tags](https://github.com/TypeStrong/typedoc/issues/125), the unescaped `<div>` and `<a>` HTML tags in the docstring break the rendering. I've attempted to fix this by surrounding them with backquotes, which will hopefully render them as code per [Markdown standards](https://daringfireball.net/projects/markdown/syntax#code).
Note that I don't have any way to preview this change so I'm just hoping it works. Maybe someone familiar with TypeDoc can verify.
I am not sure if there are any other instances of this issue in the docs, this is just the one I noticed.
> docs(directives): Fix unescaped HTML formatting

- src/directives/stateDirectives.ts
- test/stateDirectivesSpec.js
This PR addresses an issue I've got into by working with lazy loaded future states and the `ng-{style,class}` interface. 
Basically, the directive didn't update its private list of the known states when future states were resolved so the `uiSrefActive` instances that were linked before the lazy states were added to the `stateRegistry`, kept incorrectly doing a fuzzy match on all the future state's lazily registred children.
> fix(uiSrefActive): don't match fuzzy on lazy loaded future states

- src/directives/stateDirectives.ts
- test/stateDirectivesSpec.js
This is a quick, interface compliant addition to `uiSrefActive` to allow for multiple, non-sibling states to activate same class in `uiSrefActive`. For example:
```html
<div ui-sref-active="{'active': ['owner.**', 'admin.**']}">
<a ui-sref-active="active" ui-sref="admin.roles">Roles</a>
</div>
```
Will now be active for when `owner.**` state is entered, but also `admin.**`. This makes it much easier to have select parallel states share same class name without resorting to writing boilerplate code to handle that.
Closes #2524
> Feature - Add multi-state support for uiSrefActive

- package.json
PhantomJS is an unmaintained project, removed phantomjs support from package.json.
Signed-off-by: ossdev07 <ossdev@puresoftware.com>
> Angular-ui-router: Removed PhantomJS Dependency

- src/directives/stateDirectives.ts
- test/stateDirectivesSpec.ts
In most browsers, clicking links with the Alt key has a special behavior, for example, Chrome
downloads the target resource. As with other modifier keys, the router should stop the original
navigation to avoid preventing the browser’s default behavior.
When users click a link while holding the Alt key together, the browsers behave as follows.
Windows 10:
| Browser    | Behavior                                    |
|:-----------|:--------------------------------------------|
| Chrome 84  | Download the target resource                |
| Firefox 79 | Prevent navigation and therefore do nothing |
| Edge 84    | Download the target resource                |
| IE 11      | No impact                                   |
macOS Catalina:
| Browser    | Behavior                                    | …
> fix: should not transition states when alt-clicked
